language: php

php:
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

services:
  - mysql

before_install:
  - sudo mysql -e "use mysql; update user set User='forge',authentication_string=PASSWORD('forge') where User='travis'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart

before_script:
  - mysql -e 'create database if not exists forge;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - travis_retry php artisan migrate -n

script:
  - vendor/bin/phpunit